name:                decision-tree
version:             0.1.0.0
github:              "2mol/decision-tree"
license:             BSD3
author:              "Juri Chomé"
maintainer:          "juri.chome@gmail.com"
copyright:           "2018 Juri Chomé"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            misc

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/2mol/decision-tree#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- vector
- hmatrix

library:
  source-dirs: src

executables:
  decision-tree-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - decision-tree

tests:
  decision-tree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - decision-tree
